#!/bin/bash
#
# Autonomous CI/CD Pipeline for Pueblo La Dehesa
#
# Purpose: Complete automation without human interaction
# Usage:   ./scripts/autonomous-ci.sh [--section NAME] [--full] [--max-iter N] [--tolerance PCT]
#
# Features:
#  ✓ Auto-detect changes
#  ✓ Build locally
#  ✓ Auto-commit & push
#  ✓ Wait for Railway deployment
#  ✓ QA validation loop
#  ✓ Auto-rollback on critical failure
#  ✓ Zero interruptions
#

set -e

# ════════════════════════════════════════════════════════════════════════════════
# CONFIG
# ════════════════════════════════════════════════════════════════════════════════

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

SECTION="${SECTION:-}"
MODE="${MODE:-full}"  # full, section, incremental
# 2026-04-25: cap subido a 999 — iteramos hasta convergencia o tokens.
# Early-stop por convergencia: si 3 iteraciones consecutivas el diff no baja
# >= MIN_DIFF_DELTA puntos, se marca BLOCKED y se avanza.
MAX_ITERATIONS="${MAX_ITERATIONS:-999}"
MIN_DIFF_DELTA="${MIN_DIFF_DELTA:-1.0}"   # mejora mínima por iteración (en %)
STAGNATION_LIMIT="${STAGNATION_LIMIT:-3}" # iteraciones sin mejora antes de abandonar
TOLERANCE="${TOLERANCE:-2}"               # ANTES 25 — recalibrado para señal real
RAILWAY_TIMEOUT="${RAILWAY_TIMEOUT:-240}"  # 4 min
RAILWAY_URL="https://puebloladehesa-web-production.up.railway.app"
PROD_URL="https://puebloladehesa.cl"
QA_STATE=".qa-state.json"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging
LOG_FILE="$PROJECT_ROOT/.autonomous-ci.log"
exec 1> >(tee -a "$LOG_FILE")
exec 2>&1

# ════════════════════════════════════════════════════════════════════════════════
# FUNCTIONS
# ════════════════════════════════════════════════════════════════════════════════

log_info() {
  echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC} ℹ️  $@"
}

log_success() {
  echo -e "${GREEN}[$(date '+%H:%M:%S')]${NC} ✓ $@"
}

log_warn() {
  echo -e "${YELLOW}[$(date '+%H:%M:%S')]${NC} ⚠️  $@"
}

log_error() {
  echo -e "${RED}[$(date '+%H:%M:%S')]${NC} ✗ $@"
}

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 1: Code Change Detection
# ─────────────────────────────────────────────────────────────────────────────

phase_detect_changes() {
  log_info "PHASE 1: Detecting changes..."

  git fetch origin main >/dev/null 2>&1 || true
  local status=$(git status --short 2>/dev/null | wc -l)

  if [ "$status" -eq 0 ]; then
    log_warn "No uncommitted changes detected"
    return 1
  fi

  log_success "Found $status changed file(s)"
  git status --short
  return 0
}

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 2: Build Validation
# ─────────────────────────────────────────────────────────────────────────────

phase_build() {
  log_info "PHASE 2: Building..."

  if ! npm run build 2>&1 | tail -10; then
    log_error "Build failed - rolling back"
    git checkout .
    return 1
  fi

  log_success "Build completed successfully"
  return 0
}

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 3: Auto-Commit & Push
# ─────────────────────────────────────────────────────────────────────────────

phase_commit_push() {
  log_info "PHASE 3: Committing & pushing changes..."

  # Determine commit message based on changes
  local msg=$(git diff --cached --name-only 2>/dev/null | head -1)
  local component=$(echo "$msg" | sed 's/.*\///' | sed 's/\..*//')

  local commit_msg="Auto: Fix $component styling and interactions

Generated by autonomous CI/CD pipeline
- No user interaction required
- Automated validation: $(date '+%Y-%m-%d %H:%M:%S')

Co-Authored-By: Autonomous CI <noreply@anthropic.com>"

  git add -A
  git commit -m "$commit_msg" || {
    log_warn "Nothing to commit"
    return 0
  }

  git push origin main || {
    log_error "Push failed - rolling back commit"
    git reset --soft HEAD~1
    return 1
  }

  local head=$(git rev-parse --short HEAD)
  log_success "Pushed commit: $head"
  return 0
}

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 4: Wait for Railway Deployment
# ─────────────────────────────────────────────────────────────────────────────

phase_wait_railway() {
  log_info "PHASE 4: Waiting for Railway deployment..."

  local elapsed=0
  local interval=5
  local ready=0

  while [ $elapsed -lt $RAILWAY_TIMEOUT ]; do
    if curl -s "$RAILWAY_URL/api/health" >/dev/null 2>&1; then
      ready=1
      break
    fi

    echo -n "."
    sleep $interval
    elapsed=$((elapsed + interval))
  done

  echo ""

  if [ $ready -eq 0 ]; then
    log_error "Railway not ready after ${RAILWAY_TIMEOUT}s"
    return 1
  fi

  log_success "Railway deployment ready (${elapsed}s)"
  return 0
}

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 5: QA Validation
# ─────────────────────────────────────────────────────────────────────────────

phase_qa_validation() {
  log_info "PHASE 5: Running QA validation..."

  if [ -z "$SECTION" ]; then
    # Full validation
    bash "$PROJECT_ROOT/scripts/auto-build-site.sh" --watch --tolerance "$TOLERANCE" \
      2>&1 | grep -E "(Sección|Diff|DONE|BLOCKED)" | tail -20
  else
    # Single section
    bash "$PROJECT_ROOT/scripts/auto-build-site.sh" --section "$SECTION" \
      --tolerance "$TOLERANCE" 2>&1 | tail -10
  fi

  return 0
}

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 6: Status Summary
# ─────────────────────────────────────────────────────────────────────────────

phase_summary() {
  log_info "PHASE 6: Generating summary..."

  if [ ! -f "$QA_STATE" ]; then
    log_warn "QA state file not found"
    return 0
  fi

  local total=$(jq '.sections | length' "$QA_STATE")
  local done=$(jq '.sections | map(select(.status == "DONE")) | length' "$QA_STATE")
  local blocked=$(jq '.sections | map(select(.status == "BLOCKED")) | length' "$QA_STATE")

  echo ""
  echo "════════════════════════════════════════════════════════════"
  echo "QA VALIDATION SUMMARY"
  echo "════════════════════════════════════════════════════════════"
  echo "Total Sections:  $total"
  echo "DONE:            $done / $total ✓"
  echo "BLOCKED:         $blocked / $total ⏹"
  echo "Progress:        $(( done * 100 / total ))%"
  echo "════════════════════════════════════════════════════════════"
  echo ""

  # Show blocked sections
  if [ $blocked -gt 0 ]; then
    echo "BLOCKED SECTIONS (require manual review):"
    jq -r '.sections[] | select(.status == "BLOCKED") | "  • \(.id): \(.last_diff)% diff"' "$QA_STATE"
    echo ""
  fi

  log_success "Autonomous CI pipeline completed"
  return 0
}

# ─────────────────────────────────────────────────────────────────────────────
# ERROR HANDLING & ROLLBACK
# ─────────────────────────────────────────────────────────────────────────────

on_error() {
  local line=$1
  log_error "Pipeline failed at line $line"

  # Attempt rollback
  log_info "Attempting rollback..."

  if git rev-parse HEAD~1 >/dev/null 2>&1; then
    git reset --soft HEAD~1
    git checkout .
    log_success "Rollback completed"
  fi

  exit 1
}

trap 'on_error ${LINENO}' ERR

# ════════════════════════════════════════════════════════════════════════════════
# MAIN EXECUTION
# ════════════════════════════════════════════════════════════════════════════════

main() {
  log_info "╔════════════════════════════════════════════════════════╗"
  log_info "║  AUTONOMOUS CI/CD PIPELINE - PUEBLO LA DEHESA          ║"
  log_info "║  No interruptions • No confirmations • Fully automated  ║"
  log_info "╚════════════════════════════════════════════════════════╝"
  echo ""

  # Parse arguments
  while [[ $# -gt 0 ]]; do
    case $1 in
      --section)
        SECTION="$2"
        shift 2
        ;;
      --full)
        MODE="full"
        shift
        ;;
      --max-iter)
        MAX_ITERATIONS="$2"
        shift 2
        ;;
      --tolerance)
        TOLERANCE="$2"
        shift 2
        ;;
      *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
  done

  log_info "Configuration:"
  log_info "  Mode:             $MODE"
  log_info "  Section:          ${SECTION:-all}"
  log_info "  Max iterations:   $MAX_ITERATIONS"
  log_info "  Tolerance:        ${TOLERANCE}%"
  echo ""

  # Execute phases
  if phase_detect_changes; then
    phase_build && \
    phase_commit_push && \
    phase_wait_railway && \
    phase_qa_validation && \
    phase_summary
  else
    log_info "No changes to process"
    phase_qa_validation
    phase_summary
  fi
}

# ════════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ════════════════════════════════════════════════════════════════════════════════

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  main "$@"
fi
